### ISSUE TITLE
Skriv ut .doc

### ISSUE THREAD

**Issue by Gorom** [cthit/wordpress#12]
Uskriftsidan på chalmers.it tillåter .doc men skrivaren skriver ut jättemånga vita papper med små tecken på.

**Comment by bark** [comment]
Det är felaktigt att den tilåter doc tror jag. Texten är rätt.
(godkända format är ren text och PDF).
Men nuvarande digit har nog mer koll på läget.
Gorom du Kan få en liten utmaning att göra en pull request som visar en varning om man försöker skriva ut med .doc.

**Comment by bark** [comment]
Varför det inte går att skriva ut på skrivaren på doc är för att det är ett binär format som skrivaren så fall skulle behöva mjukvara för att tolka.
Andra sättet att lösa problemet vore att convertera .doc till pdf om man uptäcker att det är doc, docx eller odf

**Comment by Edholm** [comment]
Känns som att det är bättre med en varning och sen låta användaren själv konvertera till PDF så denne kan verifiera att det blev korrekt.

**Comment by bark** [comment]
Det vore bäst tror jag med båda. Att den varnar men om man endå vill skriva ut så konverterar den. För den blir endå allt som oftast som man vill ha det.

**Comment by Edholm** [comment]
@bark Lägg en feature-request här isf: https://github.com/cthit/chalmersit-rails/issues/1

Detta kommer inte implementeras i nuvarande sidan utan i den nya som utvecklas. Vi kommer nog endast avvaktivera att man får skriva ut *.doc för tillfället.

**Comment by Edholm** [comment]
Fixed in commit d0097fda29713966ae5475d9d79a81e9698143fb
